apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: <CA_CERT_BASE64>
    server: https://<K8S_API_SERVER>
  name: k8s-cluster
contexts:
- context:
    cluster: k8s-cluster
    user: jenkins
    namespace: default
  name: jenkins-context
current-context: jenkins-context
users:
- name: jenkins
  user:
    token: <JENKINS_TOKEN>
